

---
--INSERT INTO [dbo].[AEC_PARAMETER] 
--([ParaName],           [ParaValue],[ParaValue2], [ParaDesc]) VALUES
--('Bulk Discount less', 55,          350,         '< 350 PCS IN ORDER')

--INSERT INTO [dbo].[AEC_PARAMETER] 
--([ParaName],           [ParaValue],[ParaValue2], [ParaDesc]) VALUES
--('Bulk Discount more', 60,          350,         '> 350PCS IN ORDER')
---
--- for each SubCat update Additional Charges 5 columns -------------
--DECLARE @SubCategory VARCHAR(255)

--DECLARE db_cursor CURSOR FAST_FORWARD FOR
--SELECT SubCategory FROM [SubCategory]

--OPEN db_cursor  
--FETCH NEXT FROM db_cursor INTO @SubCategory  

--WHILE @@FETCH_STATUS = 0  
--BEGIN  

--	UPDATE SubCategory 
--	SET 
--		DutiesPecent = 2,
--		DocumentsMn  = 30,
--		FreightMn = 120,
--		--DiscountMarkupPecent
--		ConversionMultiplier = 22	
--	WHERE
--		SubCategory = @SubCategory
			
--      FETCH NEXT FROM db_cursor INTO @SubCategory 
--END 

--CLOSE db_cursor  
--DEALLOCATE db_cursor

--- UPDATE INVALID SUB-CATEGORY ---------------
--UPDATE P
--SET P.Name = R.[SubCategory]
--FROM Product P, [R_INVLD_SUBCAT$] R
--WHERE P.Name = R.[Invalid_SubCategory]

--UPDATE [R_INVLD_SUBCAT$]
--SET SubCategory = 'GALILEO 2 2.0'
--WHERE Invalid_SubCategory IN ('Galileo 2 2.0 IN')

--UPDATE [R_INVLD_SUBCAT$]
--SET SubCategory = 'GALILEO 1'
--WHERE Invalid_SubCategory IN ('Galileo 1 IN')

--UPDATE B SET B.SubCategory = A.[Valid Values]
--FROM [AEC_Illumination].[dbo].[Mapping2$] A, [R_INVLD_SUBCAT$] B
--WHERE B.SubCategory IS NULL
--	  AND B.Invalid_SubCategory = A.[Invaliad Values]

--SELECT B.Invalid_SubCategory, B.SubCategory, A.[Invaliad Values], A.[Valid Values]
--FROM [AEC_Illumination].[dbo].[Mapping2$] A, [R_INVLD_SUBCAT$] B
--WHERE B.SubCategory IS NULL
--	  AND B.Invalid_SubCategory = A.[Invaliad Values]

--UPDATE B SET B.SubCategory = A.SubCategory
--FROM [AEC_Illumination].[dbo].[SubCategory] A, [R_INVLD_SUBCAT$] B
--WHERE B.Invalid_SubCategory LIKE ( CONCAT('%', CONCAT(A.SubCategory, '%')) )
--	  OR A.SubCategory LIKE ( CONCAT('%', CONCAT(B.Invalid_SubCategory, '%')) )

--SELECT * 
--FROM [AEC_Illumination].[dbo].[SubCategory] A, [R_INVLD_SUBCAT$] B
--WHERE A.SubCategory LIKE ( CONCAT('%', CONCAT(B.Invalid_SubCategory, '%')) )

--SELECT * 
--FROM [AEC_Illumination].[dbo].[SubCategory] A, [R_INVLD_SUBCAT$] B
--WHERE B.Invalid_SubCategory LIKE ( CONCAT('%', CONCAT(A.SubCategory, '%')) )

--INSERT INTO CH_PARAMETER 
--	(ParaName, ParaValue, ParaDesc) VALUES 
--	('Conversion_rate_e_to_$', '1.2', 'Used on Price List report')
--GO
--INSERT INTO CH_PARAMETER 
--	(ParaName, ParaValue, ParaDesc) VALUES 
--	('COMMISSION(10%)', '10', 'Used on Price List report')
--GO
--INSERT INTO CH_PARAMETER 
--	(ParaName, ParaValue, ParaDesc) VALUES 
--	('GRANDTOTALConversion(/0.9)', '0.9', 'Used on Price List report')
--GO
-----------------------------
--INSERT INTO Product (
--	Fixture_Name,
--	Name,
--	Full_Name,
--	LED_Type,
--	OPTICAL_SYSTEM,
--	Lumen,
--	CCT,
--	N_OF_MODULES_INSTALLED,
--	mA,
--	NOMINAL_POWER,
--	Class,
--	Mounting,
--	Price_F,
--	Price_DA,
--	Price_PLM,
--	Category,
--	CreatedBy,
--	CreatedOn  )
--SELECT 
--	   [Fixture Name]
--      ,[Name]
--      ,[Full Name]
--      ,[LED - Type]
--      ,[OPTICAL SYSTEM]
--      ,[Lumen]
--      ,[CCT]
--      ,[N° OF MODULES INSTALLED]
--      ,[mA]
--      ,[NOMINAL POWER]
--      ,[CL]
--      ,[Mounting]
--      ,[F]
--      ,[DA]
--      ,[PLM],
--	  'STREET_URBAN LIGHTING_FLOODLIGHT',
--	  'Data Extraction', 
--	   getdate()
--  FROM [dbo].[R_ItaloBasicList$]
----------------------------------------
--INSERT INTO Product (
--	Fixture_Name,
--	Name,
--	Full_Name,
--	LED_Type,
--	OPTICAL_SYSTEM,
--	Lumen,
--	CCT,
--	N_OF_MODULES_INSTALLED,
--	mA,
--	NOMINAL_POWER,
--	Class,
--	Mounting,
--	Price_F,
--	Price_DA,
--	Price_PLM,
--	Category,
--	CreatedBy,
--	CreatedOn  )
--SELECT 
--	   [Fixture Name]
--      ,[Name]
--      ,[Full Name]
--      ,[LED - Type]
--      ,[OPTICAL SYSTEM]
--      ,[Lumen]
--      ,[CCT]
--      ,[N° OF MODULES INSTALLED]
--      ,[mA]
--      ,[NOMINAL POWER]
--      ,[CL]
--      ,[Mounting]
--      ,[F]
--      ,[DA]
--      ,[PLM],
--	  'STREET_URBAN LIGHTING_FLOODLIGHT',
--	  'Data Extraction', 
--	   getdate()
--  FROM [dbo].[R_TunnelList$]

-------------------------
--INSERT INTO Product (
--	Fixture_Name,
--	Name,
--	Full_Name,
--	LED_Type,
--	OPTICAL_SYSTEM,
--	Lumen,
--	CCT,
--	N_OF_MODULES_INSTALLED,
--	mA,
--	NOMINAL_POWER,
--	Class,
--	Mounting,
--	Price_F,
--	Price_DA,
--	Price_PLM,
--	Category,
--	CreatedBy,
--	CreatedOn  )
--SELECT 
--	   [Fixture Name]
--      ,[Name]
--      ,[Full Name]
--      ,[LED - Type]
--      ,[OPTICAL SYSTEM]
--      ,[Lumen]
--      ,[CCT]
--      ,[N° OF MODULES INSTALLED]
--      ,[mA]
--      ,[NOMINAL POWER]
--      ,[CL]
--      ,[Mounting]
--      ,[F]
--      ,[DA]
--      ,[PLM],
--	  'STREET_URBAN LIGHTING_FLOODLIGHT',
--	  'Data Extraction', 
--	   getdate()
--  FROM [dbo].[R_IndoorList$]

----------------
--INSERT INTO Product (
--	Fixture_Name,
--	Name,
--	Full_Name,
--	LED_Type,
--	OPTICAL_SYSTEM,
--	Lumen,
--	CCT,
--	N_OF_MODULES_INSTALLED,
--	mA,
--	NOMINAL_POWER,
--	Class,
--	Mounting,
--	Price_F,
--	Price_DA,
--	Price_PLM,
--	Category,
--	CreatedBy,
--	CreatedOn  )
--SELECT 
--	   [Fixture Name]
--      ,[Name]
--      ,[Full Name]
--      ,[LED - Type]
--      ,[OPTICAL SYSTEM]
--      ,[Lumen]
--      ,[CCT]
--      ,[N° OF MODULES INSTALLED]
--      ,[mA]
--      ,[NOMINAL POWER]
--      ,[CL]
--      ,[Mounting]
--      ,[F]
--      ,[DA]
--      ,[PLM],
--	  'STREET_URBAN LIGHTING_FLOODLIGHT',
--	  'Data Extraction', 
--	   getdate()
--  FROM [dbo].[R_SLList$]

--SELECT * FROM SYSCOLUMNS WHERE ID = OBJECT_ID('Product');


----INSERT INTO [SubCategory]
----SELECT * FROM [zOldAEC].[dbo].[SubCategory]

----INSERT INTO [dbo].[Category]
----SELECT * fROM [zOldAEC].[dbo].[Category]