

--INSERT INTO 
--	dbo.Product_Mech
--SELECT 
--	CASE
--		WHEN LEFT([POLE CODE], 3) = 'PPM'  THEN	'PM POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PDS'  THEN	'DS POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPU'  THEN	'PU POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPQ'  THEN	'PQ POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPG'  THEN	'PG POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPK'  THEN	'PK POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPN'  THEN	'PN POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPA'  THEN	'PA POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPX'  THEN	'PX POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPT'  THEN	'PT POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PCA'  THEN	'CA POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPR'  THEN	'PR POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPF'  THEN	'PF POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPS'  THEN	'PS POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPZ'  THEN	'PZ POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPE'  THEN	'PE POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPH'  THEN	'PH POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PPB'  THEN	'PB POLE'
--		WHEN LEFT([POLE CODE], 3) = 'PBB'  THEN	'BABEL'
--		WHEN LEFT([POLE CODE], 3) = 'PSP'  THEN	'AP POLE, SAFETY SERIE'
--		WHEN LEFT([POLE CODE], 4) = 'PEC5'  THEN	'EC POLE WITH A SOLE SECTION'
--		WHEN LEFT([POLE CODE], 3) = 'PEC'  THEN	'EC POLE TAPERED'
--		WHEN LEFT([POLE CODE], 5) = 'PPL5'  THEN	'PL POLE FOR LOGIKA'
--		WHEN LEFT([POLE CODE], 3) = 'PPL'  THEN	'PL POLE FOR Q'
--		WHEN LEFT([POLE CODE], 4) = 'PPD5'  THEN	'PD POLE FOR POST TOP BRACKET'
--		WHEN LEFT([POLE CODE], 3) = 'PPD'  THEN	'PD POLE FOR STAGGERED BRACKETS'
--		WHEN LEFT([POLE CODE], 3) = 'PAP'  THEN	'AP POLE, SAFETY SERIE' 
--	END,
--	 [POLE CODE]
--      ,[MODEL]
--      ,[TYPE]
--      ,[HEIGHT OUT OF GROUND          ]
--      ,[TOTAL HEIGHT]
--      ,[IN-GROUNDING SECTION]
--      ,[BASE Ø]
--      ,[POST TOP Ø]
--      ,[WALL THICKNESS]
--      ,[MATERIAL]
--      ,[PRICE ]
--	  , getdate(), 'Data Extraction', NULL, NULL, NULL
--  FROM 
--	[AEC_Illumination].[dbo].[R_PolesList$]

---
--INSERT INTO [dbo].[AEC_PARAMETER] 
--([ParaName],           [ParaValue],[ParaValue2], [ParaDesc]) VALUES
--('Bulk Discount less', 55,          350,         '< 350 PCS IN ORDER')

--INSERT INTO [dbo].[AEC_PARAMETER] 
--([ParaName],           [ParaValue],[ParaValue2], [ParaDesc]) VALUES
--('Bulk Discount more', 60,          350,         '> 350PCS IN ORDER')
---
--- for each SubCat update Additional Charges 5 columns -------------
--DECLARE @SubCategory VARCHAR(255)

--DECLARE db_cursor CURSOR FAST_FORWARD FOR
--SELECT SubCategory FROM [SubCategory]

--OPEN db_cursor  
--FETCH NEXT FROM db_cursor INTO @SubCategory  

--WHILE @@FETCH_STATUS = 0  
--BEGIN  

--	UPDATE SubCategory 
--	SET 
--		DutiesPecent = 2,
--		DocumentsMn  = 30,
--		FreightMn = 120,
--		--DiscountMarkupPecent
--		ConversionMultiplier = 22	
--	WHERE
--		SubCategory = @SubCategory
			
--      FETCH NEXT FROM db_cursor INTO @SubCategory 
--END 

--CLOSE db_cursor  
--DEALLOCATE db_cursor

--- UPDATE INVALID SUB-CATEGORY ---------------
--UPDATE P
--SET P.Name = R.[SubCategory]
--FROM Product P, [R_INVLD_SUBCAT$] R
--WHERE P.Name = R.[Invalid_SubCategory]

--UPDATE [R_INVLD_SUBCAT$]
--SET SubCategory = 'GALILEO 2 2.0'
--WHERE Invalid_SubCategory IN ('Galileo 2 2.0 IN')

--UPDATE [R_INVLD_SUBCAT$]
--SET SubCategory = 'GALILEO 1'
--WHERE Invalid_SubCategory IN ('Galileo 1 IN')

--UPDATE B SET B.SubCategory = A.[Valid Values]
--FROM [AEC_Illumination].[dbo].[Mapping2$] A, [R_INVLD_SUBCAT$] B
--WHERE B.SubCategory IS NULL
--	  AND B.Invalid_SubCategory = A.[Invaliad Values]

--SELECT B.Invalid_SubCategory, B.SubCategory, A.[Invaliad Values], A.[Valid Values]
--FROM [AEC_Illumination].[dbo].[Mapping2$] A, [R_INVLD_SUBCAT$] B
--WHERE B.SubCategory IS NULL
--	  AND B.Invalid_SubCategory = A.[Invaliad Values]

--UPDATE B SET B.SubCategory = A.SubCategory
--FROM [AEC_Illumination].[dbo].[SubCategory] A, [R_INVLD_SUBCAT$] B
--WHERE B.Invalid_SubCategory LIKE ( CONCAT('%', CONCAT(A.SubCategory, '%')) )
--	  OR A.SubCategory LIKE ( CONCAT('%', CONCAT(B.Invalid_SubCategory, '%')) )

--SELECT * 
--FROM [AEC_Illumination].[dbo].[SubCategory] A, [R_INVLD_SUBCAT$] B
--WHERE A.SubCategory LIKE ( CONCAT('%', CONCAT(B.Invalid_SubCategory, '%')) )

--SELECT * 
--FROM [AEC_Illumination].[dbo].[SubCategory] A, [R_INVLD_SUBCAT$] B
--WHERE B.Invalid_SubCategory LIKE ( CONCAT('%', CONCAT(A.SubCategory, '%')) )

--INSERT INTO CH_PARAMETER 
--	(ParaName, ParaValue, ParaDesc) VALUES 
--	('Conversion_rate_e_to_$', '1.2', 'Used on Price List report')
--GO
--INSERT INTO CH_PARAMETER 
--	(ParaName, ParaValue, ParaDesc) VALUES 
--	('COMMISSION(10%)', '10', 'Used on Price List report')
--GO
--INSERT INTO CH_PARAMETER 
--	(ParaName, ParaValue, ParaDesc) VALUES 
--	('GRANDTOTALConversion(/0.9)', '0.9', 'Used on Price List report')
--GO
-----------------------------
--INSERT INTO Product (
--	Fixture_Name,
--	Name,
--	Full_Name,
--	LED_Type,
--	OPTICAL_SYSTEM,
--	Lumen,
--	CCT,
--	N_OF_MODULES_INSTALLED,
--	mA,
--	NOMINAL_POWER,
--	Class,
--	Mounting,
--	Price_F,
--	Price_DA,
--	Price_PLM,
--	Category,
--	CreatedBy,
--	CreatedOn  )
--SELECT 
--	   [Fixture Name]
--      ,[Name]
--      ,[Full Name]
--      ,[LED - Type]
--      ,[OPTICAL SYSTEM]
--      ,[Lumen]
--      ,[CCT]
--      ,[N° OF MODULES INSTALLED]
--      ,[mA]
--      ,[NOMINAL POWER]
--      ,[CL]
--      ,[Mounting]
--      ,[F]
--      ,[DA]
--      ,[PLM],
--	  'STREET_URBAN LIGHTING_FLOODLIGHT',
--	  'Data Extraction', 
--	   getdate()
--  FROM [dbo].[R_ItaloBasicList$]
----------------------------------------
--INSERT INTO Product (
--	Fixture_Name,
--	Name,
--	Full_Name,
--	LED_Type,
--	OPTICAL_SYSTEM,
--	Lumen,
--	CCT,
--	N_OF_MODULES_INSTALLED,
--	mA,
--	NOMINAL_POWER,
--	Class,
--	Mounting,
--	Price_F,
--	Price_DA,
--	Price_PLM,
--	Category,
--	CreatedBy,
--	CreatedOn  )
--SELECT 
--	   [Fixture Name]
--      ,[Name]
--      ,[Full Name]
--      ,[LED - Type]
--      ,[OPTICAL SYSTEM]
--      ,[Lumen]
--      ,[CCT]
--      ,[N° OF MODULES INSTALLED]
--      ,[mA]
--      ,[NOMINAL POWER]
--      ,[CL]
--      ,[Mounting]
--      ,[F]
--      ,[DA]
--      ,[PLM],
--	  'STREET_URBAN LIGHTING_FLOODLIGHT',
--	  'Data Extraction', 
--	   getdate()
--  FROM [dbo].[R_TunnelList$]

-------------------------
--INSERT INTO Product (
--	Fixture_Name,
--	Name,
--	Full_Name,
--	LED_Type,
--	OPTICAL_SYSTEM,
--	Lumen,
--	CCT,
--	N_OF_MODULES_INSTALLED,
--	mA,
--	NOMINAL_POWER,
--	Class,
--	Mounting,
--	Price_F,
--	Price_DA,
--	Price_PLM,
--	Category,
--	CreatedBy,
--	CreatedOn  )
--SELECT 
--	   [Fixture Name]
--      ,[Name]
--      ,[Full Name]
--      ,[LED - Type]
--      ,[OPTICAL SYSTEM]
--      ,[Lumen]
--      ,[CCT]
--      ,[N° OF MODULES INSTALLED]
--      ,[mA]
--      ,[NOMINAL POWER]
--      ,[CL]
--      ,[Mounting]
--      ,[F]
--      ,[DA]
--      ,[PLM],
--	  'STREET_URBAN LIGHTING_FLOODLIGHT',
--	  'Data Extraction', 
--	   getdate()
--  FROM [dbo].[R_IndoorList$]

----------------
--INSERT INTO Product (
--	Fixture_Name,
--	Name,
--	Full_Name,
--	LED_Type,
--	OPTICAL_SYSTEM,
--	Lumen,
--	CCT,
--	N_OF_MODULES_INSTALLED,
--	mA,
--	NOMINAL_POWER,
--	Class,
--	Mounting,
--	Price_F,
--	Price_DA,
--	Price_PLM,
--	Category,
--	CreatedBy,
--	CreatedOn  )
--SELECT 
--	   [Fixture Name]
--      ,[Name]
--      ,[Full Name]
--      ,[LED - Type]
--      ,[OPTICAL SYSTEM]
--      ,[Lumen]
--      ,[CCT]
--      ,[N° OF MODULES INSTALLED]
--      ,[mA]
--      ,[NOMINAL POWER]
--      ,[CL]
--      ,[Mounting]
--      ,[F]
--      ,[DA]
--      ,[PLM],
--	  'STREET_URBAN LIGHTING_FLOODLIGHT',
--	  'Data Extraction', 
--	   getdate()
--  FROM [dbo].[R_SLList$]

--SELECT * FROM SYSCOLUMNS WHERE ID = OBJECT_ID('Product');


----INSERT INTO [SubCategory]
----SELECT * FROM [zOldAEC].[dbo].[SubCategory]

----INSERT INTO [dbo].[Category]
----SELECT * fROM [zOldAEC].[dbo].[Category]