

-----------------------------
--INSERT INTO Product (
--	Fixture_Name,
--	Name,
--	Full_Name,
--	LED_Type,
--	OPTICAL_SYSTEM,
--	Lumen,
--	CCT,
--	N_OF_MODULES_INSTALLED,
--	mA,
--	NOMINAL_POWER,
--	Class,
--	Mounting,
--	Price_F,
--	Price_DA,
--	Price_PLM,
--	Category,
--	CreatedBy,
--	CreatedOn  )
--SELECT 
--	   [Fixture Name]
--      ,[Name]
--      ,[Full Name]
--      ,[LED - Type]
--      ,[OPTICAL SYSTEM]
--      ,[Lumen]
--      ,[CCT]
--      ,[N° OF MODULES INSTALLED]
--      ,[mA]
--      ,[NOMINAL POWER]
--      ,[CL]
--      ,[Mounting]
--      ,[F]
--      ,[DA]
--      ,[PLM],
--	  'STREET_URBAN LIGHTING_FLOODLIGHT',
--	  'Data Extraction', 
--	   getdate()
--  FROM [dbo].[R_ItaloBasicList$]
----------------------------------------
--INSERT INTO Product (
--	Fixture_Name,
--	Name,
--	Full_Name,
--	LED_Type,
--	OPTICAL_SYSTEM,
--	Lumen,
--	CCT,
--	N_OF_MODULES_INSTALLED,
--	mA,
--	NOMINAL_POWER,
--	Class,
--	Mounting,
--	Price_F,
--	Price_DA,
--	Price_PLM,
--	Category,
--	CreatedBy,
--	CreatedOn  )
--SELECT 
--	   [Fixture Name]
--      ,[Name]
--      ,[Full Name]
--      ,[LED - Type]
--      ,[OPTICAL SYSTEM]
--      ,[Lumen]
--      ,[CCT]
--      ,[N° OF MODULES INSTALLED]
--      ,[mA]
--      ,[NOMINAL POWER]
--      ,[CL]
--      ,[Mounting]
--      ,[F]
--      ,[DA]
--      ,[PLM],
--	  'STREET_URBAN LIGHTING_FLOODLIGHT',
--	  'Data Extraction', 
--	   getdate()
--  FROM [dbo].[R_TunnelList$]

-------------------------
--INSERT INTO Product (
--	Fixture_Name,
--	Name,
--	Full_Name,
--	LED_Type,
--	OPTICAL_SYSTEM,
--	Lumen,
--	CCT,
--	N_OF_MODULES_INSTALLED,
--	mA,
--	NOMINAL_POWER,
--	Class,
--	Mounting,
--	Price_F,
--	Price_DA,
--	Price_PLM,
--	Category,
--	CreatedBy,
--	CreatedOn  )
--SELECT 
--	   [Fixture Name]
--      ,[Name]
--      ,[Full Name]
--      ,[LED - Type]
--      ,[OPTICAL SYSTEM]
--      ,[Lumen]
--      ,[CCT]
--      ,[N° OF MODULES INSTALLED]
--      ,[mA]
--      ,[NOMINAL POWER]
--      ,[CL]
--      ,[Mounting]
--      ,[F]
--      ,[DA]
--      ,[PLM],
--	  'STREET_URBAN LIGHTING_FLOODLIGHT',
--	  'Data Extraction', 
--	   getdate()
--  FROM [dbo].[R_IndoorList$]

----------------
--INSERT INTO Product (
--	Fixture_Name,
--	Name,
--	Full_Name,
--	LED_Type,
--	OPTICAL_SYSTEM,
--	Lumen,
--	CCT,
--	N_OF_MODULES_INSTALLED,
--	mA,
--	NOMINAL_POWER,
--	Class,
--	Mounting,
--	Price_F,
--	Price_DA,
--	Price_PLM,
--	Category,
--	CreatedBy,
--	CreatedOn  )
--SELECT 
--	   [Fixture Name]
--      ,[Name]
--      ,[Full Name]
--      ,[LED - Type]
--      ,[OPTICAL SYSTEM]
--      ,[Lumen]
--      ,[CCT]
--      ,[N° OF MODULES INSTALLED]
--      ,[mA]
--      ,[NOMINAL POWER]
--      ,[CL]
--      ,[Mounting]
--      ,[F]
--      ,[DA]
--      ,[PLM],
--	  'STREET_URBAN LIGHTING_FLOODLIGHT',
--	  'Data Extraction', 
--	   getdate()
--  FROM [dbo].[R_SLList$]

--SELECT * FROM SYSCOLUMNS WHERE ID = OBJECT_ID('Product');


----INSERT INTO [SubCategory]
----SELECT * FROM [zOldAEC].[dbo].[SubCategory]

----INSERT INTO [dbo].[Category]
----SELECT * fROM [zOldAEC].[dbo].[Category]